version: "2.4"
services:
  remote-interpreter:
    build:
      context: .
    working_dir: /app
    volumes:
      - .:/app
      - ./tests/resources/fluentd-setup/fluentd/etc:/fluentd/etc
      - ./tests/resources/fluentd-setup/result:/result
  integration-tests:
    build:
      context: .
    working_dir: /app
    volumes:
      - .:/app
      - ./tests/resources/fluentd-setup/fluentd/etc:/fluentd/etc
      - ./tests/resources/fluentd-setup/result:/result
    command: >
      sh -c "pip3 install tox && python3 -m tox"
  lint:
    image: ricardobchaves6/python-lint-image
    working_dir: /app
    volumes:
      - .:/app
    command: >
      sh -c "isort -rc python_fluentd_testing tests -c --diff \
        && black --check --diff python_fluentd_testing tests \
        && mypy python_fluentd_testing tests"
