version: "3.8"

x-build: &dockerfile-dev-build
  context: .
  dockerfile: Dockerfile

services:
  remote-interpreter:
    build: *dockerfile-dev-build
    working_dir: /app
    volumes:
      - .:/app
      - ./tests/resources/fluentd-setup/fluentd/etc:/fluentd/etc
      - ./tests/resources/fluentd-setup/result:/result
  integration-tests:
    build: *dockerfile-dev-build
    working_dir: /app
    volumes:
      - .:/app
      - ./tests/resources/fluentd-setup/fluentd/etc:/fluentd/etc
      - ./tests/resources/fluentd-setup/result:/result
    command: >
      sh -c "pip3 install tox && python3 -m tox"
  lint-formatter:
    build: *dockerfile-dev-build
    volumes:
      - .:/app
    command: ["./scripts/start-formatter-lint.sh"]
