name: Integration tests
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Execute integration tests
        run: docker-compose up --exit-code-from integration-tests integration-tests
